#!/usr/bin/env bash

ram=$(free -g --si | awk '/^Mem:/{print $2}')
if [ ${ram} -gt 6 ]; then
    MX="4g"
elif [ ${ram} -gt 2 ]; then
    MX="2g"
else
    MX="1g"
fi

java ${FLYWAY_JAVA_OPTS:--Xms128m -Xmx${MX}} \
    -Djava.security.egd=file:/dev/../dev/urandom \
    -cp "/flyway/lib/community/*:/flyway/drivers/*" \
    org.flywaydb.commandline.Main "$@"
exit $?
