sequenceDiagram
    participant A as Alice
    participant B as John
    Note left of A: sequence1
    A->>B: ping
    B-->>A: pong
    opt when Z
        A->>B: hi
    end
    Note left of A: sequence2
    alt if X
        A->>B: success
    else if Y
        A->>B: fail
    end
