source "https://rubygems.org"

gem "jekyll", "~> 3.5"
gem "jekyll-assets", "~> 2.3"
gem "jekyll-paginate", "~> 1.1"
gem 'therubyracer', '0.12.3'
gem "stringex", "~> 2.7"
gem "thor", "~> 0.20"
gem "uglifier", "~> 3.2"
gem "yui-compressor", "~> 0.12"
